Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.network "public_network", bridge: "wlp2s0" 
  
  config.vm.hostname = "vm-debian"

  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "Generic Debian"
    vbox.memory = 1024
  #   vbox.cpus = 1
  #   # v.linked_clone = true
  end
  
  # config.ssh.insert_key = false
  config.vm.provision "file", source: "~/.ssh/vm-1.pub", destination: "~/.ssh/me.pub"

  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # Update package list
    sudo apt update
    
    # Install Avahi daemon
    sudo apt install -y avahi-daemon
  SHELL
end

